[package]
name = "simple_shortener"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.4.4", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
once_cell = "1.9.0"
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "postgres", "macros", "offline" ] }
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.6", features = ["env-filter"] }
toml = "0.5.8"
sha2 = "0.10.1"
dashmap = { version = "5.0.0", features = ["serde"] }
async-trait = "0.1.52"
