# Port to run SimpleShortener on. Can be overridden with the `PORT` environment variable.
port = 24529
# Root of the site, this might link to your company's homepage.
root = "https://randomairborne.dev/"
# Postgres database URL.
database = "postgres://simpleshortener:simpleshortener@localhost/simpleshortener"
# A key:value list of username:sha256-hahed passwords <default admin/admin>
users = { admin = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"}
