version: "3"

services:
    simpleshortener:
        image: randomairborne/simpleshortener
        restart: always
        networks:
            - simpleshortener
        ports:
            # change external port here, not in config.toml
            - "127.0.0.1:24529:24529"
        environment:
            PORT: 24529
            DATABASE_PATH: /simpleshortener/data.rust-bincode
networks:
    simpleshortener:
